### PR TITLE
Add Arm64 Support

### PR DESCRIPTION
**Pull request by odidev**
Modified otel-collector.nomad, otel-demo.nomad and otel-agent.nomad examples files to modify the ```otel/opentelemetry-collector``` version to **0.43.0** from **0.38.0**. Since version **0.43.0** support both arm64 and amd64 platform.

Related to #4

### CODE REVIEW

**Comment by lgfa29** [comment]
Thanks for the PR @odidev.

As I mentioned in #4, I'm trying to keep these examples as close as possible to their [Kubernetes equivalent](https://github.com/open-telemetry/opentelemetry-collector/blob/main/examples/k8s/otel-config.yaml). Would you mind bumping the version there as well? Or opening an issue to get it bumped?

Then I can merge this one 🙂

**Comment by odidev** [comment]
Hi @lgfa29 

As per your suggestion I bumped the version of otel/opentelemetry-collector and raised PR.  

Please have a look: https://github.com/open-telemetry/opentelemetry-collector/pull/5015

**Comment by lgfa29** [comment]
Awesome, thank you for the extra work @odidev!

I will keep an eye on that PR, and once it's merged we can get this one updated as well 😄

**Comment by odidev** [comment]
Hi @lgfa29 

The PR has been merged and I have also updated this commit with the changes. Please have a look: https://github.com/open-telemetry/opentelemetry-collector/pull/5015

**Comment by lgfa29** [comment]
Awesome! Thank you for the work on getting both of them up-to-date 🙂

**Review by lgfa29 — APPROVED** [review]

**Pull request merged**
